
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - coworking-net

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coworking-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - coworking-net

volumes:
  postgres_data:

networks:
  coworking-net:
    driver: bridge
